landslide/landslide/models.py
from pymongo import MongoClient

#get the mongoclient
mongo = MongoClient()

#select database
db = mongo.landslide


class Data(object):

    def __init__(self, continentcode, countrycode, countryname, fatalities, hazard_type, injuries,
    landslide_size, landslide_type, latitude, longitude, storm_name, trigger, tstamp):
        self.continentcode = continentcode
        self.countrycode = countrycode
        self.countryname = countryname
        self.fatalities = fatalities
        self.hazard_type = hazard_type
        self.injuries = injuries
        self. landslide_size = landslide_size
        self.landslide_type = landslide_type
        self.latitude = latitude
        self.longitude = longitude
        self.storm_name = storm_name
        self.trigger = trigger
        self.tstamp = tstamp

    @classmethod
    def getAll(cls):
        return ""

    @classmethod
    def insertDataset(cls, continentcode, countrycode, countryname, fatalities, hazard_type,
    injuries, landslide_size, landslide_type, latitude, longitude, storm_name, trigger, tstamp):
        data = Data(continentcode, countrycode, countryname, fatalities, hazard_type, injuries, landslide_size, landslide_type, latitude, longitude, storm_name, trigger, tstamp)
        id = str(db.DataSet.insert_one(data.__dict__).inserted_id)

landslide/landslide/__init__.py
'''
The flask application package.
'''

from flask import Flask, Blueprint
from flask_session import Session
from jinja2 import Environment
from werkzeug.utils import secure_filename
app = Flask(__name__)

# Load the development configuration
app.config.from_object('config.development')

# Load the file specified by the APP_CONFIG_FILE environment variable
# Variables defined here will override those in the default configuration
app.config.from_envvar('APP_CONFIG_FILE', silent=True)

# session
app.config['SESSION_TYPE'] = 'filesystem'
Session(app)

#import the views
from view.test import test_bp
from view.data import data_bp

#add the blueprints
app.register_blueprint(test_bp)
app.register_blueprint(data_bp, url_prefix = '/data')

landslide/landslide/views.py
"""
Routes and views for the flask application.
"""

from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, request, jsonify, abort, Response, session
from landslide import app
import urllib2
import json


import models

@app.route('/')
@app.route('/home')
def home():
    return "hello"


#data view
data_bp = Blueprint('data',__name__)
app.register_blueprint(data_bp, url_prefix='/data')

@data_bp.route('/')
def index():
    result = Data.find_all()
    return render_template('show-all-data.html', data=result)

@data_bp.route('/create')
def create():
    return render_template('create-data.html')

@data_bp.route('/add', methods = ['post'])
def add():
    result = {}
    if 'action' not in request.form or request.form['action'] != 'add':
        result['error'] = True
        return redirect(url_for('data.create'), 302, result)
    #store data from post to db

@data_bp.route('/<id>')
@data_bp.route('/<id>/edit')
def edit(id):
    id_data = Data.find_by_id(id)
    if id_data == None:
        abort(404)
    else:
        return render_template('edit-data.html', data=id_data)

@data_bp.route('/<id>/update', methods = ['post'])
def update(id):
    result = {}
    if 'action' not in request.form or request.form['action'] != 'update':
        result['error'] = True
        return redirect(url_for('data.edit'), 302, result)
    #update data from post to db

@data_bp.route('/<id>/delete', methods = ['post'])
def delete(id):
    result = {}
    if 'action' not in request.form or request.form['action'] != 'delete':
        result['error'] = True
        return redirect(url_for('data.edit'), 302, result)
    #delete data from db

landslide/landslide/templates/create-data.html
{% extends "layout.html" %}

{% block title %}Create Data{% endblock %}

landslide/landslide/templates/edit-data.html
{% extends "layout.html" %}

{% block title %}Data{% endblock %}

landslide/landslide/templates/index.html
{% extends "layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>landslide</h1>
    <p class="lead">A WebApp.</p>
    <p><a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="container">
  <div class="row">
      <div class="col-md-4">
          <h2>Create</h2>
          <p>
              Create data.
          </p>
          <p><a class="btn btn-default" href="data/create">Create Data &raquo;</a></p>
      </div>
      <div class="col-md-4">
          <h2>Show</h2>
          <p>Show all.</p>
          <p><a class="btn btn-default" href="data">Show All Data &raquo;</a></p>
      </div>
      <div class="col-md-4">
          <h2>Coming Soon</h2>
          <p></p>
          <p><a class="btn btn-default" href="#">More &raquo;</a></p>
      </div>
  </div>
</div>

{% endblock %}

landslide/landslide/templates/layout.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/content/site.css" />
    <script src="/static/scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">landslide</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('test.home') }}">Home</a></li>
                    <li><a href="{{ url_for('data.create') }}">Create</a></li>
                    <li><a href="{{ url_for('data.index') }}">Show All</a></li>
                </ul>
            </div>
        </div>
    </div>
    {% block content %}{% endblock %}
    <script src="/static/scripts/jquery-1.10.2.js"></script>
    <script src="/static/scripts/bootstrap.js"></script>
    <script src="/static/scripts/respond.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

landslide/landslide/templates/show-all-data.html
{% extends "layout.html" %}

{% block title %}All Data{% endblock %}

landslide/landslide/templates/show-data.html
{% extends "layout.html" %}

{% block title %}Data{% endblock %}